# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [25]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7, 7)
tensor1

tensor([[0.4277, 0.5371, 0.6045, 0.5335, 0.4211, 0.2711, 0.7417],
        [0.4850, 0.3736, 0.1921, 0.8451, 0.4323, 0.6306, 0.2260],
        [0.7010, 0.7683, 0.1397, 0.0435, 0.8768, 0.6145, 0.3829],
        [0.6082, 0.2490, 0.6427, 0.9329, 0.8832, 0.9613, 0.4768],
        [0.4862, 0.4697, 0.2461, 0.9857, 0.6423, 0.9771, 0.1085],
        [0.8316, 0.2536, 0.9351, 0.8951, 0.9822, 0.2941, 0.8654],
        [0.0878, 0.2774, 0.7535, 0.1721, 0.4599, 0.0390, 0.7125]])

In [5]:
tensor1.shape, tensor1.dtype

(torch.Size([7, 7]), torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [26]:
# Create another random tensor
tensor2 = torch.rand(1, 7)
tensor2


tensor([[0.5329, 0.0433, 0.2218, 0.9802, 0.7159, 0.0647, 0.4610]])

In [27]:
# Perform matrix multiplication
tensor1_mult_tensor2 = torch.matmul(tensor1, tensor2.T)

In [28]:
tensor1_mult_tensor2

tensor([[1.5692],
        [1.6002],
        [1.3244],
        [2.3061],
        [1.8732],
        [2.6600],
        [1.0549]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [34]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
tensor1_mult_tensor2 = torch.matmul(tensor1, tensor2.T)
tensor1_mult_tensor2


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [35]:
from IPython.core.async_helpers import dedent
# Set random seed on the GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.cuda.manual_seed(1234)
device


'cuda'


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [40]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)
tensor1, tensor2


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [41]:
# Perform matmul on tensor_A and tensor_B
tensor1_mult_tensor2 = torch.matmul(tensor1, tensor2.T)
tensor1_mult_tensor2, tensor1_mult_tensor2.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [43]:
# Find max
max = tensor1_mult_tensor2.max()

# Find min
min = tensor1_mult_tensor2.min()

max.item(), min.item()


(0.5617256760597229, 0.3647301495075226)

### 9. Find the maximum and minimum index values of the output of 7.

In [47]:
# Find arg max
max_index_values = tensor1_mult_tensor2.argmax()


# Find arg min
min_index_values = tensor1_mult_tensor2.argmin()
max_index_values, min_index_values

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [48]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor2 = tensor1.squeeze()


# Print out tensors and their shapes
tensor1, tensor2


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))